##############################
#    TCC PUC Minas (2020)    #
# Alessandro Cezar Lorençone #
##############################

name: 'DataWarehouse'
version: '1.0'

profile: 'datawarehouse'

# Paths
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# run hooks
on-run-start:

on-run-end:

# Models
models:
  DataWarehouse:
    materialized: table
    staging:
      materialized: view
      schema: staging

# Seeds
seeds:
  DataWarehouse:
    enabled: true
    schema: staging    
