version: '3.7'

services:
  metabase:
    image: metabase/metabase:v0.36.6
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER}
      - MB_DB_PASS=${POSTGRES_PASS}
      - MB_DB_HOST=localhost
      - MB_JETTY_PORT=4000
    ports:
      - "4000:4000"
